name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install shadcn/ui components
        run: |
          npm install @radix-ui/react-slot@^1.0.2 @radix-ui/react-tabs@^1.0.4 class-variance-authority@^0.7.0 clsx@^2.0.0 tailwind-merge@^2.0.0 tailwindcss-animate@^1.0.7
          mkdir -p src/components/ui
          cp -r node_modules/@radix-ui/react-tabs src/components/ui/tabs.jsx
          cp -r node_modules/@radix-ui/react-slot src/components/ui/slot.jsx
          cp -r node_modules/class-variance-authority src/components/ui/class-variance-authority
          cp -r node_modules/clsx src/components/ui/clsx
          cp -r node_modules/tailwind-merge src/components/ui/tailwind-merge
          cp -r node_modules/tailwindcss-animate src/components/ui/tailwindcss-animate
        env:
          CI: true

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
